[package]
name = "smithay-bar-example"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
env_logger = "0.11.8"
rusttype = "0.9.3"
smithay-client-toolkit = "0.19.2"
wayland-client = "0.31.8"
